### ISSUE TITLE
Keybinder: Grab input text

### ISSUE THREAD

**Issue by IngwiePhoenix** [kueblc/LDT#12]
I would like to be able to react on the entering of special characters. For instance, when the user types in `{`, I would like to automatically add a closing `}`.

Previously I had tried using LDT in tandem with [BehaveJS](http://jakiestfu.github.io/Behave.js/)...but that did not go well, because Behave.JS "ate" the backspace key; which would prevent `api.update()` to be called.

**Comment by IngwiePhoenix** [comment]
I managed to pair Behave.JS and LDT at last. I had to re-assign the keydown and keypress event.

**Comment by pygy** [comment]
@IngwiePhoenix do you remember exactly what had to be re-assigned? I'd like to pair these libraries as well...
