### ISSUE TITLE
Github Pages not found

### ISSUE THREAD

**Issue by AviFS** [kueblc/LDT#19]
### Issue
The page linked is: https://kueblc.github.com/LDT/. But it gives *404 - There isn't a GitHub Pages site here.*

### Thoughts
Github Pages isn't listed as an active environment in the lower left, so maybe it got disabled via settings?

Or maybe it's just not working because there isn't an `index.html` in root?

**Comment by pylover** [comment]
This is just the wrong URL, the working URL is https://kueblc.github.io/LDT/

**Comment by kueblc** [comment]
Thanks for the heads up, I'll update this soon
