### ISSUE TITLE
Caret misaligned on iPhone

### ISSUE THREAD

**Issue by dy** [kueblc/LDT#22]
![image](https://user-images.githubusercontent.com/300067/141657232-7edcf986-587a-484b-af8c-34014e87c09b.png)

Caret is displayed with unfortunate offset

**Comment by kueblc** [comment]
Thank you for the report! If you have any suggestions I'd be happy to hear them.

I will try to get access to an iPhone to test on.

**Comment by kueblc** [comment]
Looks like the cause is [`text-size-adjust`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust). iOS Safari seems to apply text scaling to only the display area, and not the input.

Thanks for pointing this out @dy!
