### ISSUE TITLE
Suggestion: A dedicated layer for the caret allows a fully transparent textarea (and thus vivid colors)

### ISSUE THREAD

**Issue by pygy** [kueblc/LDT#26]
[As seen here](https://flems.io/#0=N4IgtglgJlA2CmIBcBmAnAOgGwBYA0IAzvAgMYAu8UyIGAFuWLCAYaQE4D2szSA2gAY8AgLoEAZhASFkfUADsAhmERJaDJixClO8ynpoAeAIRROFAJ4AHeAAINsAHwAdeYfIRyCRwBkAIgAqtqQAruyEnOy2UPBgnIYA9B5e8C5uhOQW3q4JAFS2AfAAHuSK7PCKfvA67IrkkRikhISutvkA7uye+rYARha2AMLcEPK2ANIh8L0IUQBMAgCMc635AApl5Lac4rb+AXjRIYqwtrAQpPDyxFC2IfIxUQDiaz4Abii2ig+2ALIAkgFVrY1lw3tB4IRbBkspDbOJIrZyg94F15ABzL62SglMoVbZjepWba7RS2KzlWztTx0aEcbiwXplFpjXIJVw5fLEcgeDFQiycELBb7k2CKAbU8i0tkc+QYWBQciHeWKs6KXokWzAVrkxQwUbopC2HBWIoAblcAF9ZSqlbZbeTysqFVscaVyopnarGmEIuxhnpFKNUVqdQi9ABaQgQABe8CNiywptsxggYCskVKegtY1seSRkNjdhO6MiNLA0XgNgeUN0WLi8k4hCsikut3DWxluY7EfEyikFiNDabLcuKbTGfYWfIOdsZ2DEbo8Ag6IYCYAHKazXncgADU272zyeBUKjwxEQeBoYKcdN1Wy72K7qGkRQhYi2SCEE4r48qPR9PA5DtCeYxihYqKEF21ryK4DpuniZLarm+Z9jwTKkAA1ueUS9Fw7TEOEVI0oKWzsOiTJtOyuY6LAkRGuQtTXC2yJbKm6aZt8M46vmYCKJhdiEGEdhSsWsBWHQZIQFCdHtLYVyCqu0KcLYnjRJwkLyAA5FsMzmNhonbCE5BWMZaoQVEXZznktH0UiFGKAAFEILl4BgcwAJTjhxU5cWa0E2i62LFO6FRIEgxBkB4dbIXOGGYeiXD3FAEa2ewRrkUyjnLAA7Iciw5euhxzOghwCO5Hmzn0kSPBGtRQBA75GigW5WoFqoIR64URnEMZRiQ1TRWMsV9K2CVJQ8qXcHZmVOeuQi2IsAgLXMOALeViwAKyVTqvQ1aidV6o1hDNa18gwZy0JAby6L8oK0J0IKCraVsVjgcRUp3PI0h3UKklvMWtilpwtwehErLUXBQUjZwAPsOIslGm+9RVRm0ZDRlJB1BAAM5hdcpBRSdgjT1nB9S2+oYlG7rkAmZ1znx5GjEaAhVbDqII5w7RGqMngQCcVWk3174HZFg1Go2x5VSL7D9VFEu6PAePtVsYoaqcI1o3zuhI70ESwMZSs6kSLNVQg4i07YrM6tSip0Amy0AKRVUuK5rotTtVQ1zbgTz33BlVe1FFGsYGkae3sLVQeC71EZByHMZh9VkcHdHOoRiBvSYZ4cecMH0aJxi4f7bLac0b6dlusrsEEx1IWIaGuaM+izNW6jeoNUXbe7SXpu7WNiWCg8fe5qR5zHgrUs6uUBfxkeitVZA8gZ9AUoOwIzs6kvi7LqultLRvbNw5z3P2NAMTyNXUOqiN8cF0nEdR3nMdk7n+eh13j+p8-6eZ9n5BvwTg-Eub9A690WsmfW0A+hiiwtXfMMJpBfCsG9S8tx6g3jAP+V0nABLXCotfLYzZviNFvNgr0RCWxymjC3DWOo0pGgAMQ5V6DlK+tdKEkIyGiTEI0GG2EYeILA1tzoq2hFQjA8gQhgA1FEPh010oCKgHMKA7CHTELlHUdgIQECNznPwxhm11xzDUUFH04RIgBlKMGOR9CFEMSYsQ1iL8+p3w-oaZOT9zS-2mP-QB99P4gLLnFPOQDAkp1Lj-XM3s3rinDnROBOpXZ73XpvXM5tLYiLnBTTuHiTTeNzFrDGXw9bcENlVE23dcztDoJ4eAUZRxzyJlVW2a8PaHx1H1UYMQihIAjIsauDpzF+isUGY8URhmIhGjE32ql-ZT1ETXAAAgJCw4hagqChDMUY2ERob0OCgfZ7THZai-rLDJU06KKJmGNM0ME5ybSOfNE5wAzmXMro4liVwZwwXxvBeuXUEShChAAantKECx-pdDWPGbYRw4KK7pQ1AiSkI1vhpmxjrGBOzFpQlGJIeQdTUZNm1vIXW+tyk9wiRGDJEURi3EWMmRi3wnHfMXmUFuy9aURnKptemN49DfKNM4EA6IRUtNXvbLJ2xj6I1qTAK41dEiINSK4QwbAuhWHIGkfMhRcQeiqDUOoDQABWLI2hUi6DyK4fQBjDHHhMKYMwQwLGWMCDYU4SR7ECIcKAxxTjnEuNcM8yUQwvHeJ8b4twARAlZLYAAQiEKQUAoRRs-GMmFqboSZAQLcUiplVbihDKGqIZJOr4lGAW8yqJVjUXEPcCgEA6x6tCpUaokRjXsEcsFfVFRDgsUIrYDyyFnDkHzP8AAcoCAhsFyBvDKMgiAtgAC82JamEBzByMdCQBXcJCBQeSDV6hRD8AAeV+Fu+dUQvkAVXWYUI2DGgekoAAUQQNgxyIqGpvBFTtWdV6jImTMne8w0jvlPoqK+993zP0gCJr+zdJk8R6AwIoFBVwoCDFqQqRy+bjJ-tHQBtWmoQMPvAxwSD8A32xBgyK4jsAENbpveQVD6GHhYeTY5ejBHt0FliWOQy5aySSlpAAJQCAAQVsGe34XwfjPtKKQWkdZ6NbqExgZjE6QbwAwOUfj8AOM4d1KxQ4Qmh2Ifo6x6smHsNQEckJnjCQd3MuuOIEMhlBgAGVPPZthFCDBgoohUE8JEJjyGWOkDFM0Cdyg7Crq0kFLStgwXqci4oaLsXEOpai4QGLKgV22C0lpRDTnsRhDGDsXYvQk2wAAaMcRJBYBKeqNnDEcz4QQHKAiIoamAUVAwM2RrzWsIFbQsQErznyskl2O0Gqlq0O9d7YoDAnQ0MFZFZV8VOoeI7sGO+eoFYIV+h1ABo7ljoVjJDKRsDKGKN1Co9BvQsHv2MfLpC0ZNjGg5by3F2wIqztQsDDYrbb2RkXc+2h6zhm7P3puxF598AW1aZiLB39HkTsLoBwVgHH3xlWYw9DxysPH13agzRp7X6cZo6qgDr76XcuxfW9oRFIOdSWchwT2zjkcfg-Gej2dpW0oGi+LAUsVq6BgEvZjhRo2G1DW7ZW4yhw8N2gHSGYdW7CMLu4FAAIuCrhQlXSrxotnkeQkQ1rqIx52h67wYb4zhEMD1DwUWRyivyA8ctx18I5A-AQHEOIQ4UXff+-EBO+A7Qg-pZDwH09CoLe8YJegpc3uMjRFD6iK4lxNfkBRd2yQPu-cB4K6zVPMfdiGCPBH23Bv5RXHRJ9AAZI3svReK-bAVDX64deMRSm3AXjIbeQVgv56OsfHhxDdut13wgfAB-l5ECmZdRvO-6+uHPzrg-Q8iCdyFKx3yh19A9JhBPpXGJpjXXYBAvflO7BV-PGI-mVKGVnl6wy7uc81KkPAKf1e1+EB7wb1pErx1xn0AM+lH3IHH2N3KDiABkJ1AP-w30L23090T26UvzVDTwagD0z3kGz1nVHTzywPL3DzklXWn3-3ALoH6Sjy31jwVAK0QLt2oP6X7033L1sEr2Dzbzj1URILbzIIjAjDoPLz4OEKHRz1HX91-xtyQJ4NDzIMX2MGXw7113kOj14IVB3zdH3wAi8jwgqBPxz1KxCCsCgHu0-BBn9zQXERZRz2IPYJQOL0MFXQUIYP4PnyHxHxHSgL8OYIN2QPoPEB3zSwy3y1XTV3YAwAhD0H9wsEckoLtyCIXzQNHQCPXy8O313xKD0K2BX3UOSKyIDx31GHGRbQKySMCOKJCITwuj8NKw7naziBwNsI0RZHH2IIA1GEIiGjWHyLUJnxSLb0XwAB9RijwdFYAnDgiuC3DNDFCI8Zjy9h8h1fDx8AMNECtidyMEdqMP0RUNFXtx9R0NE6dwjfsoiYiL4J8EiqjMiOCRi0jyAzjdDoUD9V0ziyjUQKiKC-8ijHjt8E90jjIC0Yjg0px414AUUf87D5BDgejUQ+itg0D6jLRN1Z00MIBwSq1V0hNEMsSMB78jdQTjICSrBsSzCLDKBZd8D5cNdCC50F13cCt1N50DYjZGSZC5kq0GSTjyA0oFd5AC1ldSTVdmR1dgTeMYhKB2Al4RIU8NQ09X8UVMChMpCmSohx44RV13cBtUFyBHItJnBXAtJnjSsk9MCpEZEQwdgbwDYwBrgNSAM+Iihr8S9DgIVr8pSujmSS9twl1uDgwADr8gCAzVi+S-Dx9BcThQgxQaTDJWlb95JWxaRShegNSvd0yfB69PpV0FpKtuQCs2DMzgJsNYTcMA8iy3Dgy+AIBSiUQihT1J9CsTTyAtJlcqygIQVFgh0vJ4V+k1jSzR1szczaQQVV0cpbAIxbB7N1Qcyb9ktptuQvITl1wpTR16j+TTswh3SazjxZ96zqClzRyb8NzeMMhIgFS7BEpKM09tSzgxy113x4QyhSzXS9z003SbV4UvSbUAB+L890o0P8y+DUrcvw1Lbge3D8m1MFAZDU9TfCe3bUkMp8sFExHPS0eSWAD8dYhondSLCoKIQyGZcUDU43b49gAACQCF+B8AKyKylNKxniAh7VbSRC5kIASFog6KjOtSW1IVwtZL62W2QoKwQsZPuTnCunIACDTHgFIkckJIBx43RJ1BUsRVpMbV0EcgZJkuCERVx1RF0yrFgQMy5x1AMp2NuwRyR203s1EowHZKmAG0DR-wWnUzFh0vkE8xpg8g8jwCspkp5yBzxyU2TTN1n1EGCv5wMtpzCIZwiMKySxYshDYsMm2XkAMgUqiDrCxzgJ02Cu5HkpUCUvrTpKbXkD0uAASu+0Z3iwBy0ktDitsHqNKxlMGhF1OCU2+HRDhAwUE1EqCoFx3VGEixCFyVsFWT2jKFuHd09OMh4s4CsAsASBbAyHgF9VqExBbygC4CsEOCAlIC3W5PUw7hfQBj0B8Gkn0HV3wtKwyCjTmq2WQsgiNF0BZPgCuqgNzDnHOpgEuu+Rus2vGVgyBXfBFUOAqp8pquCrnBKoUqUs0shVarnBauCoBqgCBuutuquFRFg0iwuEwihvhDlyqrhr+pksRrKuMmUopMmXYDRrauZqxpxvIBBruq7RFVWTMHaFghYDJsqt0v0oMtktKsUrpsJKpPu2ZoxqprZp+s5vxu5pAA-0FulvMPu2hpOA-D-QMtK15g8BODPlXHOD3gNC3WwpIDwpMJ3V+E83+BfSNE6oPV6oxAGufxTy0hcvgCSwpBWqRIsBz3Op5FTPZu7Q22FIOqDvdv6qho1Jhvl3gEjP5O5J0wDpsCnAsB+yd04B8C5lREGHSx-y8mX3i19qS1Tv4tHU1upNLvPIgs3JzzUq3UNsJWNtOFqTNrdhui3Trvuz0oxNHXKHICmyxLxgxPzA9UdzNWBE6G6BtX6CGBGDGEmGmFmFsFdRWDjQ9S2DtP2F9X9XnCDRuC+keFsHDQ+Dk2jUBGBCeBVvuyzWdyuCLCiHWVvALHRB0QXWKCJmaCqqhFVJbUQkNQ7WPVrVlCTqqpBAlK7SRB0UhARKHJQnyEnWnSslsAAyxNZPXQxOsh3SvX5mdShBFnmsFXYCUB4GDqpqXV1NsEAq0ggCSyNCYox2vQlNExfUqKmKqgA20QQE83YFIAKz4BED4YXQEfgF+DW1XWAHUprjnEJKaNXWgd0oQaQVFrnF9KiCkfaykahC0Zks2IKwMb4CkZ3wiDCEuCqgMqkaEdIA03fDoG7UMdsZkqkZkasHMcQcXz+LklE3gHRBfSKCsCNIAD0jSQVCAQUzSAASDs1SczYK6S7JTh7h-x2wQJ4J0J7tex4RjAE1TgUYI00Ys0w4LSdELSEFJdfWtqqqQkl+wlOMbS+Xd3Ix0eqbPUviAUlxtXLhuphRpRhm2I241pimppoxnRjRuwerTxtbIxucbk+Z7xix3fDIezNfLyRZjxoCKbKR9x9GlJnUBRjShmjuPJxBtx2UOcTpyhxdSetVBIDVCALVNIQwOgFAXwQIQyyFeSUJ1EBSvQRIT595szaAZdLSHQGICTD0LSRwdugoUSsB2oY9QplkNRsYEBg1dtVFyIbtITftOBlBgh2wPgQgQlKwEQdh35sHMKq7dSMjWyyjfY2jEAF7EAOp0KmFEyxKn7Jnbly7dgEHfRIy3nEyjndjLnGy+HSjeylHEVNHGlrHVdQViHNjGzTjGViDe7VlindlqnTlrlxFc4pK37f7FnEAfBtUdWfHKVzjNVvnHbaESls5ykrWmk1R8mkWkaUljAf1r4UhoSE4UzJcRR6moCCW5Ghm1SqqIZxdRm8Zn14Kx1kyvTcywneGxluHHVygeVn-Nkk4Vywgdy5yUzJy7yoaPyzYAKkasW2l87el6IiKhUKKwQalqm5muq+nfl+LVKndVi10RU8eHKlQPKsYAq9mDAYqyNpGumzFmq7ti4xipq+Wo5lCHdclyljt-6pyi6pWvGsGkVCGloQWhdoxmmyWw0lGv0Vqtd9ixCVDQGg90Ggm-7QNEms9716qi92d2m69mNxFO9-nRIITMF0S1SKAZdQ4pcICWFioEVRwIZVN2xGiexbET5cLFxfxdxYualYJacv+HONxQuDxN5Ajkj4BfDqJOcMiwcGBfSF2Xed2A+NJOcWlKpNJymPJflIpKq8lMpSgCpFakeOcL-SgBpVsJpcoCVO2VJKqLpRsvpSSmCZDsVpthFP56ZaSWJej0YbU9hFZeANZDZOELK3ZHUI5Q5R2fKJ2U5EBC5fhG5OBaSx5Gz2wZ5ez6lfhFzVlbMX5MRITJAE9pcxm4yqIeFRmpAZFK8vROTDFYpcz3FOZAlIlHUPjrFdUClITqlWqWlKBBlJlTD5xLeDlUYGlaE2mHlDAPlApfRd4vQYVUVEV4iOT6VdmeGOVc+RVK0UD0S95l5t52UVwADAAKUIBnoZet1gfCDfdzF9ezR4SNASC0kcn-KQBNJNL4BNM8xNMIBEFGL4HCa0hEA8lyC0lGJFTW4282+2+cF2+cH28O-CZFVO9yBFQSDrZktGZsNRGW74EUAjBjAkwjAAC0AB9EQO79oEQNkL7uca02RZbiMf867k0qAd75wDADyf89HkFT7lNshIVPME09kZwBII7k04V1wWHgnqm8TyERpZbvb-H+H7YUSRRMnzzaiddv9ADQYZoSbqITJoXz9eb4KrRRB5bpZPgCME0mH1n4q8-LuFbtH27nbvbg7o7k7s7i7q79bzb5wO7h7p7ynkAN7j7tnxHv7vMFHtXjHk07H3H5wKAEFa7gHoHkH0HkQEFUYx2HHungymhKQf7k07UZwa0I3k06l5wT9ZwDyJAPAC0ZwTHkFUnn3wPmShn4hS4Znx7xXqmnQLBYnsnsn3IO7loe72H53zHpzNnzgDnvP7nk51wAjeQADYLY9SoiPJFpbFFztMX2j0DR9fq8gPV8geNCwf4OzKF7TeDxQcpnUcboX1vjEgDOj7vuSbFiofv49Qf7NkfoCcfyf6fo0wgWD8gefxf3MAXibuB1f4bmuWUJzTvhoPUk9vSp5wb7VVwLQStwBmgHMCwA5QkAAgEAJaDwAKBYsNAdFloB0CCoDAagJzM3HK4cdeUW4P-gNB8oyA1AAgJAHMEWDgDIBIAJQCoBgFNAZABAeAfoHIA0BwBIgS0EAA).

On the left is LDT's source, on the right a demo that highlights what's been added.

Please note that this is whipped out of an old project of mine where I tweaked LDT quite a bit. I've however imported the latest version of `TextareaDecorator()` which is where the meat of the patch lies (There's also some CSS, some of which may not be necessary).

**Comment by kueblc** [comment]
Hi Pierre,

Thanks for sharing your suggestion! I appreciate the time you took to describe your enhancement.

I believe you will be happy to find that the current LDT does in fact have an essentially fully transparent textarea, thanks to the addition of the [caret-color](https://github.com/kueblc/LDT/blob/bb6bd75fbcf9b7426c9bc3d20983a11652cdcfb4/lib/TextareaDecorator.css#L24) property. This allows us to set the native caret color independent of the text color.

Reimplementing native behavior like the caret is something I'd like to avoid for LDT. Other rich text solutions like CodeMirror already take the approach of reimplementing standard behaviors; what sets LDT apart is behaving like a native component without all the added weight.

Thanks again for sharing your thoughts and please don't hesitate if you have any others to share.

**Comment by pygy** [comment]
That's awesome, I didn't know about `caret-color`.

I understand you'd rather avoid reimplementing native stuff, I didn't know you could do without (the aforementioned hacking dates back to 2015-16, and I hadn't tried updating LDT in the mean time... Since you were mentioning a semi-transparent textarea, I thought things hadn't changed in that regard).

**Comment by pygy** [comment]
That's awesome, I didn't know about `caret-color`.

I understand you'd rather avoid reimplementing native stuff, I didn't know you could do without (the aforementioned hacking dates back to 2015-16, and I hadn't tried updating LDT in the mean time... Since you were mentioning a semi-transparent textarea, I thought things hadn't changed in that regard).
