### ISSUE TITLE
iOS text shadow

### ISSUE THREAD

**Issue by honkskillet** [kueblc/LDT#9]
I know it's not one of the officially supported browsers, but I tried it in iOS (UIWebView).  There is a shadow of the text.  It looks like maybe the underlying textarea is being render in light gray and is slightly offset a couple pixels.  Also it is murderously slow, even for a small bit of text.  On the plus side, it reacts to touch events properly (no 300ms delay, drag selection ok, etc.).  These are issues that make other similar solutions like codeMirror unusable on iOS.

**Comment by Yaffle** [comment]
Did you try using `    -webkit-text-fill-color: transparent;` instead of semi-transparent colors ?
```
    -webkit-text-fill-color: transparent;
```

**Comment by Yaffle** [comment]
Modern browsers support `caret-color` property.
So, it is possible to set `color` to `transparent` and `caret-color` to `black`.

**Comment by kueblc** [comment]
Brilliant @Yaffle, perhaps it's time to revive this project

**Comment by kueblc** [comment]
This has been implemented, thanks @Yaffle
